import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html className='h-full antialiased' lang='en'>
      <body className='flex min-h-full flex-col'>{children}</body>
    </html>
  )
}
