import type { Metadata, Viewport } from 'next'
import { balsamiq } from '@/lib/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  interactiveWidget: 'overlays-content',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html className={`${balsamiq.variable} h-full antialiased`} dir='ltr' lang='en'>
      <body className='flex min-h-full flex-col'>{children}</body>
    </html>
  )
}
